### ISSUE TITLE
Uninitialized stream (IOError) in puzzle.rb:81

### ISSUE THREAD

**Issue by artyrcheek** [pacso/aoc_rb#25]
Hi, thanks so much for making this template, I've been loving it.
Today (2022 7th) running `aoc prep` **worked as usual for part 1**
but it seems rerunning `aoc prep` for **part 2 now results in this error**.
Im on version `aoc_rb (0.2.5)`
```
$ arthurcheek@arthurs-mbp advent-of-code-2022 % aoc prep      
challenges/2022/07/input.txt already exists, skipping
/Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:81:in `closed?': uninitialized stream (IOError)
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:81:in `open'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:81:in `process_article'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:73:in `block in parse_and_save_instructions'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.9/lib/nokogiri/xml/node_set.rb:234:in `block in each'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.9/lib/nokogiri/xml/node_set.rb:233:in `upto'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.9/lib/nokogiri/xml/node_set.rb:233:in `each'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:73:in `each_with_index'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:73:in `parse_and_save_instructions'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/puzzle.rb:53:in `fetch_instructions'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/app.rb:58:in `fetch_instructions'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/app.rb:42:in `fetch'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/app.rb:142:in `prep'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /Users/arthurcheek/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aoc_rb-0.2.5/lib/aoc_rb/app.rb:148:in `<top (required)>'
        from bin/aoc:35:in `require'
        from bin/aoc:35:in `<main>'
```

**Comment by artyrcheek** [comment]
I get the same issue if i run
`aoc prep 2022 7`

**Comment by artyrcheek** [comment]
it seems i can fix it by deleting the whole folder then re running `prep`

**Comment by artyrcheek** [comment]
Doesn't seem to be working for day 8 😔

**Comment by artyrcheek** [comment]
My bad, the issue was caused because for one of my solutions i created a class name `File`, renaming this to something else has fixed the issue

**Comment by pacso** [comment]
Hi @artyrcheek,

I'm glad you're enjoying using this gem! 😄 

As you've discovered ... [File](https://ruby-doc.org/core-2.5.0/File.html) is part of Ruby core. As such, if you rewrite over the class then lots of things will break. Well done for finding the issue though, and best of luck with the rest of this year's puzzles!

**Comment by artyrcheek** [comment]
Yeah, a bit of a silly mistake on my part 🥴
Thanks & happy AOC'ing! 🎄🎁
